apiVersion: v1
kind: Service
metadata:
    name: my-headless
spec: 
    clusterIP: None
    selector:
       app: nginx-1
    ports:
    - name: http
      port: 8090
      targetPort: 80

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
      - name: nginx
        image: harshajain/ip_app:2
        imagePullPolicy: Always
        ports:
        - containerPort: 80